-- a) Nombre de commandes passées
SELECT COUNT(NBON)
FROM COMMANDE;

-- b) Montant total et montant des commandes
SELECT C.NBON, SUM(A.PRIXUNITAIRE*AP.QUANTITE)-C.MONTANTDEDUCTION AS MONTANT_COMMANDE, SUM(A.PRIXUNITAIRE*AP.QUANTITE)-C.MONTANTDEDUCTION+6.99+C.FRAISLIV AS MONTANT_TOTAL
FROM COMMANDE C, ARTICLE A, APPARTENIR AP
WHERE C.NBON = AP.NBON
    AND AP.REFERENCE = A.REFERENCE
GROUP BY C.NBON, C.MONTANTDEDUCTION, C.FRAISLIV;

-- c) Montant de ventes par produits
SELECT A.REFERENCE, SUM(A.PRIXUNITAIRE*AP.QUANTITE) as MONTANT_VENTES
FROM ARTICLE A, APPARTENIR AP
WHERE AP.REFERENCE = A.REFERENCE
GROUP BY A.REFERENCE
ORDER BY A.REFERENCE ASC;

-- d) Nombre de commandes passées par client
SELECT CL.NCLIENT, COUNT(CD.NBON) AS COMMANDE_PASSEE
FROM CLIENT CL, COMMANDE CD
WHERE CL.NCLIENT = CD.NCLIENT
GROUP BY CL.NCLIENT;

-- e) Nombre de commandes passées et montant total par genre (H et F) des clients
SELECT CL.CIVILITE, COUNT(DISTINCT(CD.NBON)) AS COMMANDE_PASSEE, SUM(A.PRIXUNITAIRE*AP.QUANTITE)+6.99*COUNT(DISTINCT(CD.NBON))+SUM(DISTINCT(CD.FRAISLIV))-SUM(DISTINCT(CD.MONTANTDEDUCTION)) AS MONTANT_TOTAL
FROM CLIENT CL, COMMANDE CD, APPARTENIR AP, ARTICLE A
WHERE CL.NCLIENT = CD.NCLIENT
    AND CD.NBON = AP.NBON
    AND AP.REFERENCE = A.REFERENCE
GROUP BY CL.CIVILITE;

-- f) Obtenir le prix unitaire du produit n°950728
SELECT PRIXUNITAIRE
FROM ARTICLE 
WHERE REFERENCE = '950728';

-- g) Obtenir les clients ayant commandé le produit n°950728 avec la quantité commandée
SELECT CL.NCLIENT, CL.NOM, CL.PRENOM, AP.QUANTITE
FROM CLIENT CL, COMMANDE CD, APPARTENIR AP, ARTICLE A
WHERE CL.NCLIENT = CD.NCLIENT
    AND CD.NBON = AP.NBON
    AND AP.REFERENCE = A.REFERENCE
    AND A.REFERENCE = '950728';